import { createOctokit } from "../octokit";

/**
 * Creates a pull request on GitHub with the generated code changes.
 *
 * Flow:
 *   1. Get the SHA of the latest commit on the default branch (main).
 *   2. Create a new branch: prdbot/issue-{issueNumber}.
 *   3. Commit each file change to the new branch using the Git Data API.
 *   4. Open a pull request from the new branch to main.
 *   5. Return the pull request URL.
 *
 * @param {object} params
 * @param {string} params.githubToken - GitHub OAuth token
 * @param {string} params.owner - Repository owner
 * @param {string} params.repo - Repository name
 * @param {number} params.issueNumber - The GitHub issue number
 * @param {string} params.issueTitle - The issue title (used for PR title)
 * @param {Array<{path: string, action: string, content: string}>} params.files - Generated file changes
 * @returns {Promise<{success: boolean, prUrl?: string, error?: string}>}
 */
export async function createPullRequest({ githubToken, owner, repo, issueNumber, issueTitle, files }) {
  if (!githubToken) {
    return { success: false, error: "No GitHub token available to create PR" };
  }

  if (!files || files.length === 0) {
    return { success: false, error: "No files to commit" };
  }

  const octokit = createOctokit(githubToken);
  const branchName = `prdbot/issue-${issueNumber}`;

  try {
    // Step 1: Get the SHA of the latest commit on the main branch
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: "heads/main",
    });
    const baseSha = refData.object.sha;

    // Step 2: Create a new branch from main
    try {
      await octokit.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      });
    } catch (branchError) {
      if (branchError.status === 422) {
        // Branch already exists — delete it and recreate
        await octokit.git.deleteRef({
          owner,
          repo,
          ref: `heads/${branchName}`,
        });
        await octokit.git.createRef({
          owner,
          repo,
          ref: `refs/heads/${branchName}`,
          sha: baseSha,
        });
      } else {
        throw branchError;
      }
    }

    // Step 3: Get the base tree SHA for creating a new tree
    const { data: commitData } = await octokit.git.getCommit({
      owner,
      repo,
      commit_sha: baseSha,
    });
    const baseTreeSha = commitData.tree.sha;

    // Step 4: Create blobs for each file
    const treeItems = [];
    for (const file of files) {
      const { data: blobData } = await octokit.git.createBlob({
        owner,
        repo,
        content: file.content,
        encoding: "utf-8",
      });

      treeItems.push({
        path: file.path,
        mode: "100644",
        type: "blob",
        sha: blobData.sha,
      });
    }

    // Step 5: Create a new tree with all the file changes
    const { data: newTree } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: baseTreeSha,
      tree: treeItems,
    });

    // Step 6: Create a commit pointing to the new tree
    const commitMessage = `[PRDBot] Implement: ${issueTitle}\n\nAuto-generated code changes for issue #${issueNumber}.`;
    const { data: newCommit } = await octokit.git.createCommit({
      owner,
      repo,
      message: commitMessage,
      tree: newTree.sha,
      parents: [baseSha],
    });

    // Step 7: Update the branch ref to point to the new commit
    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${branchName}`,
      sha: newCommit.sha,
    });

    // Step 8: Open the pull request
    const prBody = `## PRDBot Auto-Generated PR

This pull request was automatically generated by **PRDBot's Code Agent** to implement the changes described in issue #${issueNumber}.

### Source Issue
Closes #${issueNumber}

### Files Changed
${files.map(f => `- \`${f.path}\` (${f.action})`).join("\n")}

---
*Generated by PRDBot — Automated Code Generation Agent.*`;

    const { data: prData } = await octokit.pulls.create({
      owner,
      repo,
      title: `[PRDBot] ${issueTitle}`,
      body: prBody,
      head: branchName,
      base: "main",
    });

    return {
      success: true,
      prUrl: prData.html_url,
      prNumber: prData.number,
    };
  } catch (err) {
    console.error("[PR_CREATE_ERROR]", err.message);
    return { success: false, error: err.message };
  }
}
