import { createOctokit } from "../octokit";

/**
 * Execute the appropriate GitHub action based on the PRDBot evaluation result.
 *
 * @param {object} parsed - The parsed JSON evaluation result from the agent
 * @param {object} context - Execution context
 * @param {boolean} context.simulated - Whether this is a simulation
 * @param {string|null} context.githubToken - GitHub OAuth token
 * @param {string} context.repoFullName - e.g. "owner/repo"
 * @param {number} context.issueNumber - The GitHub issue number
 * @param {function} context.broadcast - Broadcast function for live updates
 * @returns {object} Tool execution result
 */
export async function executeTool(parsed, context) {
  const { simulated, githubToken, repoFullName, issueNumber, broadcast } = context;
  const action = parsed.overall?.action || "none";

  if (action === "none" || parsed.overall?.status === "compliant") {
    return { success: true, message: "No action required. Issue is compliant." };
  }

  if (action === "comment_on_issue") {
    return await postCombinedComment(repoFullName, issueNumber, parsed, githubToken, simulated, broadcast);
  }

  if (action === "flag_for_review") {
    await addReviewLabel(repoFullName, issueNumber, githubToken, simulated, broadcast);
    return await postCombinedComment(repoFullName, issueNumber, parsed, githubToken, simulated, broadcast);
  }

  return { success: false, error: `Unknown action: ${action}` };
}

/**
 * Builds the combined markdown comment string across all three passes.
 */
function buildCombinedComment(parsed) {
  const { drift, ai_review, rule_enforcement, overall } = parsed;

  let comment = `## PRDBot Analysis Report\n\n`;
  comment += `**Overall Status:** ${overall.status.toUpperCase()}\n`;
  comment += `**Summary:** ${overall.summary}\n\n`;
  comment += `---\n\n`;

  if (drift) {
    comment += `### Drift Assessment\n`;
    comment += `- **Status:** ${drift.status.toUpperCase()} (Score: ${drift.score}/100)\n`;
    if (drift.status !== "compliant") {
      comment += `- **Type:** ${drift.type}\n`;
      comment += `- **Conflict:** ${drift.conflicts_with}\n`;
      comment += `- **Reason:** ${drift.reason}\n`;
      if (drift.suggested_alternative) {
        comment += `- **Recommendation:** ${drift.suggested_alternative}\n`;
      }
    }
    comment += `\n`;
  }

  if (ai_review) {
    comment += `### Quality Review\n`;
    comment += `- **Status:** ${ai_review.status.toUpperCase()} (Alignment Score: ${ai_review.alignment_score}%)\n`;
    if (ai_review.findings && ai_review.findings.length > 0) {
      comment += `\n**Findings:**\n`;
      ai_review.findings.forEach(finding => {
        comment += `- ${finding}\n`;
      });
    }
    if (ai_review.missing && ai_review.missing.length > 0) {
      comment += `\n**Missing Information:**\n`;
      ai_review.missing.forEach(miss => {
        comment += `- ${miss}\n`;
      });
    }
    comment += `\n`;
  }

  if (rule_enforcement && rule_enforcement.status !== "compliant") {
    comment += `### Rule Enforcement\n`;
    comment += `- **Status:** ${rule_enforcement.status.toUpperCase()}\n\n`;
    
    if (rule_enforcement.rules_violated && rule_enforcement.rules_violated.length > 0) {
      comment += `**Violated Rules:**\n`;
      rule_enforcement.rules_violated.forEach(rule => {
        comment += `> ${rule}\n\n`;
      });
    }

    if (rule_enforcement.suggested_rewrite) {
      comment += `**Suggested Revision:**\n\`\`\`\n${rule_enforcement.suggested_rewrite}\n\`\`\`\n`;
    }
    comment += `\n`;
  }

  comment += `---\n`;
  comment += `*Generated by PRDBot — Automated Product Requirements Analysis.*\n`;

  return comment;
}

/**
 * Post a formatted PRDBot comment on the GitHub issue.
 */
async function postCombinedComment(repoFullName, issueNumber, parsed, githubToken, simulated, broadcast) {
  await broadcast?.({
    type: "tool_call",
    message: `Initiating comment protocol.`,
    tool: "comment_on_issue",
    args: { action: parsed.overall?.action },
  });

  const commentBody = buildCombinedComment(parsed);

  if (simulated) {
    return {
      success: true,
      simulated: true,
      message: "Comment would have been posted (simulation mode)",
      commentBody,
    };
  }

  if (!githubToken) {
    return {
      success: false,
      error: "No GitHub token available to post comment",
    };
  }

  try {
    const [owner, repo] = repoFullName.split("/");
    const octokit = createOctokit(githubToken);

    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: commentBody,
    });

    return { success: true, message: "Comment posted successfully" };
  } catch (err) {
    console.error("[COMMENT_ERROR]", err);
    return { success: false, error: err.message };
  }
}

/**
 * Add a 'prdbot-review' label to the issue for human review.
 */
async function addReviewLabel(repoFullName, issueNumber, githubToken, simulated, broadcast) {
  await broadcast?.({
    type: "tool_call",
    message: `Applying review flag.`,
    tool: "flag_for_review",
    args: {},
  });

  if (simulated) {
    return {
      success: true,
      simulated: true,
      message: "Label would have been added (simulation mode)",
    };
  }

  if (!githubToken) {
    return {
      success: false,
      error: "No GitHub token available to add label",
    };
  }

  try {
    const [owner, repo] = repoFullName.split("/");
    const octokit = createOctokit(githubToken);

    try {
      await octokit.issues.addLabels({
        owner,
        repo,
        issue_number: issueNumber,
        labels: ["prdbot-review"],
      });
    } catch (labelErr) {
      if (labelErr.status === 422) {
        await octokit.issues.createLabel({
          owner,
          repo,
          name: "prdbot-review",
          color: "FBCA04",
          description: "Flagged by PRDBot for manual review",
        });

        await octokit.issues.addLabels({
          owner,
          repo,
          issue_number: issueNumber,
          labels: ["prdbot-review"],
        });
      } else {
        throw labelErr;
      }
    }

    return { success: true, message: "Review label applied successfully" };
  } catch (err) {
    console.error("[FLAG_ERROR]", err);
    return { success: false, error: err.message };
  }
}
